services:
  opensearch-node:
    image: opensearchproject/opensearch:2.16.0
    platform: linux/amd64
    container_name: opensearch-node
    environment:
      discovery.type: single-node
      plugins.security.disabled: true
      cluster.name: "opensearch-cluster" # Name the cluster
      node.name: opensearch-node # Name the node that will run in this container
      bootstrap.memory_lock: true # Disable JVM heap memory swapping
      OPENSEARCH_JAVA_OPTS: "-Xms2g -Xmx2g" # Set min and max JVM heap sizes to at least 50% of system RAM
      DISABLE_INSTALL_DEMO_CONFIG: true # Prevents execution of bundled demo script which installs demo certificates and security configurations to OpenSearch
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
volumes:
  opensearch-data:
  